path_to_engine: "/home/antoine/Documents/RockDetection/weights/yolov5s_400.engine"
class_map: [Rock, Crater]
num_classes: 2
buffer_size: 2
image_width: 640
image_height: 480
nms_tresh: 0.45
conf_tresh: 0.5
max_output_bbox_count: 1000
rotated_bounding_boxes: false